ALTER TYPE "JobApplicantOptionalFieldKey" ADD VALUE IF NOT EXISTS 'FIRST_NAME';
ALTER TYPE "JobApplicantOptionalFieldKey" ADD VALUE IF NOT EXISTS 'LAST_NAME';
ALTER TYPE "JobApplicantOptionalFieldKey" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "JobApplicantOptionalFieldKey" ADD VALUE IF NOT EXISTS 'RESUME_URL';
ALTER TYPE "JobApplicantOptionalFieldKey" ADD VALUE IF NOT EXISTS 'CURRENT_COMPANY';
ALTER TYPE "JobApplicantOptionalFieldKey" ADD VALUE IF NOT EXISTS 'YEARS_OF_EXPERIENCE';
