import type { OngoingCommitteePerson, OngoingRecruitmentJob } from "@/features/hr/recruitment/ongoing-recruitment/types";

export const ongoingCommitteePeople: OngoingCommitteePerson[] = [
  { id: "committee-0", fullName: "User1", role: "HR Manager" },
  { id: "committee-1", fullName: "Meron Tadesse", role: "HR Business Partner" },
  { id: "committee-2", fullName: "Abel Girma", role: "Engineering Manager" },
  { id: "committee-3", fullName: "Saron Bekele", role: "Senior Product Manager" },
  { id: "committee-4", fullName: "Nathan Tesfaye", role: "Head of Design" },
  { id: "committee-5", fullName: "Rahel Assefa", role: "Talent Acquisition Specialist" },
  { id: "committee-6", fullName: "Dawit Kebede", role: "Finance Business Partner" },
];

function createCandidate(candidate: {
  id: string;
  fullName: string;
  phone: string;
  listedAt: string;
  rating: number;
  portfolioUrl: string;
  linkedinUrl: string;
  resumeUrl: string;
  salaryExpectation: string;
  noticePeriod: string;
  location: string;
  summary: string;
  strengths: string[];
  concerns: string[];
  recommendation: string;
}) {
  return {
    id: candidate.id,
    fullName: candidate.fullName,
    phone: candidate.phone,
    listedAt: candidate.listedAt,
    rating: candidate.rating,
    answers: [
      { id: `${candidate.id}-a1`, label: "Full Name", value: candidate.fullName, type: "text" as const },
      { id: `${candidate.id}-a2`, label: "Phone Number", value: candidate.phone, type: "text" as const },
      { id: `${candidate.id}-a3`, label: "Current Location", value: candidate.location, type: "text" as const },
      { id: `${candidate.id}-a4`, label: "Salary Expectation", value: candidate.salaryExpectation, type: "number" as const },
      { id: `${candidate.id}-a5`, label: "Notice Period", value: candidate.noticePeriod, type: "text" as const },
      { id: `${candidate.id}-a6`, label: "Portfolio", value: candidate.portfolioUrl, type: "link" as const },
      { id: `${candidate.id}-a7`, label: "LinkedIn Profile", value: candidate.linkedinUrl, type: "link" as const },
      { id: `${candidate.id}-a8`, label: "Resume / CV", value: candidate.resumeUrl, type: "file" as const },
      { id: `${candidate.id}-a9`, label: "Why Join Us", value: candidate.summary, type: "textarea" as const },
    ],
    aiAnalysis: {
      score: candidate.rating,
      summary: candidate.summary,
      strengths: candidate.strengths,
      concerns: candidate.concerns,
      recommendation: candidate.recommendation,
    },
  };
}

export const ongoingRecruitmentJobs: OngoingRecruitmentJob[] = [
  {
    id: "ongoing-backend-001",
    title: "Senior Backend Engineer",
    statusLabel: "Active Job",
    department: "Technical Dept.",
    interviewedCount: 2,
    onInterviewCount: 2,
    shortlistedCount: 40,
    waitlistedCount: 20,
    topMatch: {
      fullName: "Jessica Parker",
      phone: "+251 967 97 3799",
      experience: "2 Years",
      salaryExpectation: "20,000",
      canStart: "Feb 03, 2025",
      matchScore: 90,
    },
    interviewCommittee: [],
    interviews: [
      {
        id: "i-1",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        interviewStatus: "interviewed",
        status: "waitlisted",
        rating: 90,
        committeeReviews: [
          { memberId: "committee-0", memberName: "User1", note: "Strong communication and clear backend reasoning.", rate: 88 },
          { memberId: "committee-2", memberName: "Abel Girma", note: "Good system design depth. Needs tighter API validation examples.", rate: 84 },
          { memberId: "committee-5", memberName: "Rahel Assefa", note: "Professional and responsive throughout the process.", rate: 86 },
        ],
      },
      {
        id: "i-2",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        interviewStatus: "interviewed",
        status: "waitlisted",
        rating: 90,
        committeeReviews: [
          { memberId: "committee-0", memberName: "User1", note: "Needs stronger examples on production incident handling.", rate: 79 },
          { memberId: "committee-1", memberName: "Meron Tadesse", note: "Good attitude, but experience fit is mixed.", rate: 76 },
          { memberId: "committee-6", memberName: "Dawit Kebede", note: "Compensation expectations are manageable for the level.", rate: 81 },
        ],
      },
      {
        id: "i-3",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        interviewStatus: "scheduled",
        status: "pending",
        interviewDate: "Feb 24, 2025",
        interviewTime: "10:00 AM",
        rating: 90,
        committeeReviews: [
          { memberId: "committee-0", memberName: "User1", note: "", rate: null },
          { memberId: "committee-2", memberName: "Abel Girma", note: "", rate: null },
        ],
      },
      {
        id: "i-4",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        interviewStatus: "scheduled",
        status: "pending",
        interviewDate: "Feb 24, 2025",
        interviewTime: "10:00 AM",
        rating: 90,
        committeeReviews: [
          { memberId: "committee-0", memberName: "User1", note: "", rate: null },
          { memberId: "committee-4", memberName: "Nathan Tesfaye", note: "", rate: null },
        ],
      },
    ],
    shortlisted: [
      createCandidate({
        id: "s-1",
        fullName: "Sarah Williams",
        phone: "+251 930 73 9847",
        listedAt: "Dec 15, 2025",
        rating: 90,
        portfolioUrl: "https://portfolio.example.com/sarah-williams",
        linkedinUrl: "https://linkedin.com/in/sarah-williams",
        resumeUrl: "https://files.example.com/sarah-williams-resume.pdf",
        salaryExpectation: "20,000 ETB",
        noticePeriod: "30 days",
        location: "Addis Ababa",
        summary: "Very strong backend candidate with solid API design and ownership history.",
        strengths: ["Strong API architecture", "Good stakeholder communication", "Clear production ownership"],
        concerns: ["Needs deeper database scaling examples"],
        recommendation: "Move forward to interview round with engineering panel.",
      }),
      createCandidate({
        id: "s-2",
        fullName: "Naomi Bekele",
        phone: "+251 921 54 2221",
        listedAt: "Dec 16, 2025",
        rating: 87,
        portfolioUrl: "https://portfolio.example.com/naomi-bekele",
        linkedinUrl: "https://linkedin.com/in/naomi-bekele",
        resumeUrl: "https://files.example.com/naomi-bekele-resume.pdf",
        salaryExpectation: "22,000 ETB",
        noticePeriod: "Immediate",
        location: "Adama",
        summary: "Strong engineering fundamentals with good communication and clear product understanding.",
        strengths: ["Good architecture fundamentals", "Fast learner", "Clear communication"],
        concerns: ["Leadership depth still emerging"],
        recommendation: "Keep shortlisted and assess team fit in interview.",
      }),
      createCandidate({
        id: "s-3",
        fullName: "Daniel Hailu",
        phone: "+251 945 11 7788",
        listedAt: "Dec 17, 2025",
        rating: 84,
        portfolioUrl: "https://portfolio.example.com/daniel-hailu",
        linkedinUrl: "https://linkedin.com/in/daniel-hailu",
        resumeUrl: "https://files.example.com/daniel-hailu-resume.pdf",
        salaryExpectation: "18,500 ETB",
        noticePeriod: "21 days",
        location: "Addis Ababa",
        summary: "Reliable backend engineer with strong delivery consistency and moderate scaling exposure.",
        strengths: ["Consistent delivery", "Good code quality", "Practical debugging"],
        concerns: ["Needs stronger distributed systems exposure"],
        recommendation: "Shortlist for technical validation interview.",
      }),
      createCandidate({
        id: "s-4",
        fullName: "Martha Alemu",
        phone: "+251 912 88 4455",
        listedAt: "Dec 18, 2025",
        rating: 82,
        portfolioUrl: "https://portfolio.example.com/martha-alemu",
        linkedinUrl: "https://linkedin.com/in/martha-alemu",
        resumeUrl: "https://files.example.com/martha-alemu-resume.pdf",
        salaryExpectation: "19,000 ETB",
        noticePeriod: "14 days",
        location: "Bahir Dar",
        summary: "Good fundamentals and collaboration skills, though the profile is slightly lighter on large-scale systems.",
        strengths: ["Good collaboration", "Solid fundamentals", "Quick ramp-up potential"],
        concerns: ["Limited experience on high-scale systems"],
        recommendation: "Keep in shortlist as a backup strong-fit profile.",
      }),
    ],
    waitlisted: [
      createCandidate({
        id: "w-1",
        fullName: "Helen Worku",
        phone: "+251 930 73 9847",
        listedAt: "Dec 19, 2025",
        rating: 79,
        portfolioUrl: "https://portfolio.example.com/helen-worku",
        linkedinUrl: "https://linkedin.com/in/helen-worku",
        resumeUrl: "https://files.example.com/helen-worku-resume.pdf",
        salaryExpectation: "21,000 ETB",
        noticePeriod: "30 days",
        location: "Addis Ababa",
        summary: "Reasonable experience but weaker alignment on backend depth for this role.",
        strengths: ["Responsive communication", "Reliable background"],
        concerns: ["Shallower backend ownership", "Limited systems depth"],
        recommendation: "Do not advance for this role.",
      }),
      createCandidate({
        id: "w-2",
        fullName: "Selam Awoke",
        phone: "+251 933 12 0021",
        listedAt: "Dec 20, 2025",
        rating: 76,
        portfolioUrl: "https://portfolio.example.com/selam-awoke",
        linkedinUrl: "https://linkedin.com/in/selam-awoke",
        resumeUrl: "https://files.example.com/selam-awoke-resume.pdf",
        salaryExpectation: "20,500 ETB",
        noticePeriod: "45 days",
        location: "Hawassa",
        summary: "Candidate shows potential, but current role fit is below the shortlist threshold.",
        strengths: ["Strong attitude", "Good communication"],
        concerns: ["Limited direct stack experience", "Needs more production depth"],
        recommendation: "Reject for now.",
      }),
    ],
  },
  {
    id: "ongoing-frontend-002",
    title: "Senior Frontend Engineer",
    statusLabel: "Active Job",
    department: "Technical Dept.",
    interviewedCount: 2,
    onInterviewCount: 1,
    shortlistedCount: 22,
    waitlistedCount: 12,
    topMatch: {
      fullName: "Mina Bekele",
      phone: "+251 910 22 1188",
      experience: "4 Years",
      salaryExpectation: "26,000",
      canStart: "Mar 12, 2025",
      matchScore: 88,
    },
    interviewCommittee: [],
    interviews: [
      {
        id: "i-5",
        fullName: "Samuel Tadesse",
        phone: "+251 923 10 9876",
        interviewStatus: "interviewed",
        status: "waitlisted",
        rating: 87,
        committeeReviews: [
          { memberId: "committee-0", memberName: "User1", note: "Strong frontend ownership and practical tradeoff thinking.", rate: 91 },
          { memberId: "committee-4", memberName: "Nathan Tesfaye", note: "Works well cross-functionally with design.", rate: 89 },
          { memberId: "committee-3", memberName: "Saron Bekele", note: "Clear product thinking and strong stakeholder communication.", rate: 87 },
        ],
      },
      {
        id: "i-6",
        fullName: "Mina Bekele",
        phone: "+251 910 22 1188",
        interviewStatus: "scheduled",
        status: "pending",
        interviewDate: "Mar 03, 2025",
        interviewTime: "02:30 PM",
        rating: 88,
        committeeReviews: [
          { memberId: "committee-0", memberName: "User1", note: "", rate: null },
          { memberId: "committee-3", memberName: "Saron Bekele", note: "", rate: null },
        ],
      },
    ],
    shortlisted: [
      createCandidate({
        id: "s-9",
        fullName: "Mina Bekele",
        phone: "+251 910 22 1188",
        listedAt: "Jan 10, 2026",
        rating: 88,
        portfolioUrl: "https://portfolio.example.com/mina-bekele",
        linkedinUrl: "https://linkedin.com/in/mina-bekele",
        resumeUrl: "https://files.example.com/mina-bekele-resume.pdf",
        salaryExpectation: "28,000 ETB",
        noticePeriod: "Immediate",
        location: "Addis Ababa",
        summary: "Strong frontend systems thinker with solid ownership on complex product surfaces.",
        strengths: ["Strong product sense", "Excellent UI architecture", "Good design collaboration"],
        concerns: ["Needs stronger mentorship examples"],
        recommendation: "Advance to interview quickly.",
      }),
      createCandidate({
        id: "s-10",
        fullName: "Samuel Tadesse",
        phone: "+251 923 10 9876",
        listedAt: "Jan 12, 2026",
        rating: 86,
        portfolioUrl: "https://portfolio.example.com/samuel-tadesse",
        linkedinUrl: "https://linkedin.com/in/samuel-tadesse",
        resumeUrl: "https://files.example.com/samuel-tadesse-resume.pdf",
        salaryExpectation: "25,000 ETB",
        noticePeriod: "30 days",
        location: "Addis Ababa",
        summary: "Strong frontend craft and performance awareness with good execution consistency.",
        strengths: ["Performance optimization", "Good component design", "Strong ownership"],
        concerns: ["Needs more leadership evidence"],
        recommendation: "Keep shortlisted and validate product judgment in interview.",
      }),
      createCandidate({
        id: "s-11",
        fullName: "Yared Alemu",
        phone: "+251 911 44 8822",
        listedAt: "Jan 14, 2026",
        rating: 84,
        portfolioUrl: "https://portfolio.example.com/yared-alemu",
        linkedinUrl: "https://linkedin.com/in/yared-alemu",
        resumeUrl: "https://files.example.com/yared-alemu-resume.pdf",
        salaryExpectation: "24,000 ETB",
        noticePeriod: "21 days",
        location: "Adama",
        summary: "Good frontend engineer with practical delivery depth and clean implementation examples.",
        strengths: ["Clean implementation", "Strong collaboration", "Reliable delivery"],
        concerns: ["Less exposure to design systems at scale"],
        recommendation: "Shortlist as a viable interview candidate.",
      }),
      createCandidate({
        id: "s-12",
        fullName: "Rahel Tesfaye",
        phone: "+251 929 10 5544",
        listedAt: "Jan 15, 2026",
        rating: 85,
        portfolioUrl: "https://portfolio.example.com/rahel-tesfaye",
        linkedinUrl: "https://linkedin.com/in/rahel-tesfaye",
        resumeUrl: "https://files.example.com/rahel-tesfaye-resume.pdf",
        salaryExpectation: "26,000 ETB",
        noticePeriod: "14 days",
        location: "Addis Ababa",
        summary: "Balanced frontend profile with solid UI quality and dependable communication.",
        strengths: ["UI quality", "Clear communication", "Dependable execution"],
        concerns: ["Needs deeper architecture examples"],
        recommendation: "Proceed to interview round.",
      }),
    ],
    waitlisted: [
      createCandidate({
        id: "w-9",
        fullName: "Mikias Wondimu",
        phone: "+251 910 55 0012",
        listedAt: "Jan 18, 2026",
        rating: 83,
        portfolioUrl: "https://portfolio.example.com/mikias-wondimu",
        linkedinUrl: "https://linkedin.com/in/mikias-wondimu",
        resumeUrl: "https://files.example.com/mikias-wondimu-resume.pdf",
        salaryExpectation: "23,000 ETB",
        noticePeriod: "30 days",
        location: "Addis Ababa",
        summary: "Good delivery record, but current fit is slightly below shortlisted candidates.",
        strengths: ["Consistent execution", "Good communication"],
        concerns: ["Shallower product thinking", "Less design systems depth"],
        recommendation: "Reject for this role.",
      }),
      createCandidate({
        id: "w-10",
        fullName: "Betelhem Kassa",
        phone: "+251 923 10 9876",
        listedAt: "Jan 19, 2026",
        rating: 82,
        portfolioUrl: "https://portfolio.example.com/betelhem-kassa",
        linkedinUrl: "https://linkedin.com/in/betelhem-kassa",
        resumeUrl: "https://files.example.com/betelhem-kassa-resume.pdf",
        salaryExpectation: "22,500 ETB",
        noticePeriod: "45 days",
        location: "Hawassa",
        summary: "Capable frontend engineer, but not as strong as the current shortlist for this opening.",
        strengths: ["Good UI implementation", "Positive collaboration"],
        concerns: ["Limited complex frontend systems exposure"],
        recommendation: "Reject for this role.",
      }),
    ],
  },
];
