import type { ProbationEmployee, ProbationSummaryStat } from "@/features/hr/onboarding/probation/types";

export const probationSummaryStats: ProbationSummaryStat[] = [
  { id: "on-probation", label: "On Probation", value: "3", icon: "calendar" },
  { id: "avg-performance", label: "Avg Performance", value: "57%", icon: "trend" },
  { id: "pending-reviews", label: "Pending Reviews", value: "3", icon: "award" },
];

export const probationEmployees: ProbationEmployee[] = [
  {
    id: "probation-1",
    name: "Jessica Parker",
    role: "Full Stack Developer",
    department: "Technical Dept.",
    avatarText: "JP",
    startDate: "Dec 30, 2025",
    endDate: "Dec 30, 2025",
    daysRemaining: "77 Days",
    automatedScore: "87%",
    reviews: [
      {
        id: "review-1",
        dateLabel: "First Review Date",
        dateValue: "Dec 30, 2025",
        scoreLabel: "Review Score",
        scoreValue: "45%",
        reviewer: "John Smith",
        note: "+2 more",
        followUpLabel: "Next Review",
        followUpValue: "Dec 8, 2025",
      },
      {
        id: "review-2",
        dateLabel: "Second Review Date",
        dateValue: "Dec 30, 2025",
        scoreLabel: "Review Score",
        scoreValue: "45%",
        reviewer: "John Smith",
        note: "+2 more",
        followUpLabel: "Total Score",
        followUpValue: "90%",
      },
    ],
    kpiMetrics: [
      { id: "kpi-1", label: "Code Quality", score: "85/90 (30%)", progress: 94 },
      { id: "kpi-2", label: "Project Delivery", score: "95/100 (40%)", progress: 95 },
      { id: "kpi-3", label: "Team Collaboration", score: "88/85 (30%)", progress: 92 },
    ],
    overallScore: "90%",
  },
  {
    id: "probation-2",
    name: "Jessica Parker",
    role: "Full Stack Developer",
    department: "Technical Dept.",
    avatarText: "JP",
    startDate: "Dec 30, 2025",
    endDate: "Dec 30, 2025",
    daysRemaining: "77 Days",
    automatedScore: "87%",
    reviews: [],
    kpiMetrics: [],
    overallScore: "90%",
  },
  {
    id: "probation-3",
    name: "Jessica Parker",
    role: "Full Stack Developer",
    department: "Technical Dept.",
    avatarText: "JP",
    startDate: "Dec 30, 2025",
    endDate: "Dec 30, 2025",
    daysRemaining: "77 Days",
    automatedScore: "87%",
    reviews: [],
    kpiMetrics: [],
    overallScore: "90%",
  },
];
