import type { RelatedFormItem, RelatedFormsStat, RelatedFormType } from "@/features/hr/talent/related-forms/types";

export const relatedFormTypes: RelatedFormType[] = [
  { id: "employee-satisfaction", icon: "😊", label: "Employee Satisfaction Survey", formsCount: 1 },
  { id: "grievance", icon: "📋", label: "Grievance Form", formsCount: 1 },
  { id: "discipline-evaluation", icon: "⚠️", label: "Discipline Evaluation Form", formsCount: 1 },
  { id: "skill-gap", icon: "📊", label: "Skill Gap Assessment Form", formsCount: 1 },
  { id: "training-request", icon: "📚", label: "Training Request Form", formsCount: 1 },
  { id: "training-feedback", icon: "✍️", label: "Training Feedback Form", formsCount: 1 },
];

export const relatedFormsStats: RelatedFormsStat[] = [
  { id: "total-forms", label: "Total Forms", value: "6", icon: "file" },
  { id: "active-forms", label: "Active Forms", value: "6", icon: "check" },
  { id: "total-questions", label: "Total Questions", value: "110", icon: "questions" },
  { id: "total-responses", label: "Total Responses", value: "344", icon: "responses" },
];

export const allRelatedForms: RelatedFormItem[] = [
  {
    id: "q1-employee-satisfaction-survey",
    icon: "😊",
    title: "Q1 2024 Employee Satisfaction Survey",
    status: "active",
    category: "Employee Satisfaction Survey",
    description: "Comprehensive quarterly survey covering job satisfaction, work environment, and management",
    questions: 25,
    sections: 5,
    responses: 156,
    modifiedAt: "2024-02-10",
  },
  {
    id: "employee-grievance-submission-form",
    icon: "📋",
    title: "Employee Grievance Submission Form",
    status: "active",
    category: "Grievance Form",
    description: "Confidential form for employees to report workplace concerns and grievances",
    questions: 12,
    sections: 3,
    responses: 8,
    modifiedAt: "2024-01-15",
  },
  {
    id: "discipline-review-assessment",
    icon: "⚠️",
    title: "Discipline Review Assessment",
    status: "active",
    category: "Discipline Evaluation Form",
    description: "Structured evaluation form for documenting and reviewing disciplinary actions",
    questions: 18,
    sections: 4,
    responses: 12,
    modifiedAt: "2024-02-05",
  },
  {
    id: "technical-skills-gap-analysis",
    icon: "📊",
    title: "Technical Skills Gap Analysis",
    status: "active",
    category: "Skill Gap Assessment Form",
    description: "Comprehensive assessment of technical skills and competency gaps",
    questions: 30,
    sections: 6,
    responses: 89,
    modifiedAt: "2024-01-28",
  },
  {
    id: "training-program-request-form",
    icon: "📚",
    title: "Training Program Request Form",
    status: "active",
    category: "Training Request Form",
    description: "Standard form for employees to request external training and certifications",
    questions: 10,
    sections: 2,
    responses: 45,
    modifiedAt: "2024-02-12",
  },
  {
    id: "training-completion-feedback",
    icon: "✍️",
    title: "Training Completion Feedback",
    status: "active",
    category: "Training Feedback Form",
    description: "Post-training evaluation to assess effectiveness and gather participant feedback",
    questions: 15,
    sections: 3,
    responses: 34,
    modifiedAt: "2024-02-08",
  },
];
