import type {
  JobApplicationFormResponseDto,
  JobResponseDto,
  ListJobsResponse,
} from '@/types/recruitment';

const baseApplicationForm: JobApplicationFormResponseDto = {
  id: 'app-form-1',
  jobId: 'job-1',
  applicantFields: [
    {
      id: 'field-1',
      key: 'PHONE',
      label: 'Phone Number',
      type: 'TEXT',
      enabled: true,
      required: true,
      helpText: null,
      options: [],
      order: 1,
    },
    {
      id: 'field-2',
      key: 'EMAIL',
      label: 'Email Address',
      type: 'TEXT',
      enabled: true,
      required: true,
      helpText: null,
      options: [],
      order: 2,
    },
  ],
  sections: [
    {
      id: 'section-1',
      key: 'EDUCATION',
      label: 'Education',
      type: 'SECTION',
      enabled: true,
      required: false,
      helpText: null,
      options: [],
      fields: [
        {
          key: 'INSTITUTION',
          label: 'Institution',
          type: 'TEXT',
          required: false,
          helpText: null,
          options: [],
          order: 1,
        },
      ],
      order: 1,
    },
  ],
  customFields: [
    {
      id: 'custom-1',
      label: 'Portfolio URL',
      type: 'TEXT',
      required: false,
      helpText: 'Share a link to your work.',
      options: [],
    },
  ],
};

const baseJob: Omit<JobResponseDto, 'requestForm' | 'job'> = {
  applicationForm: baseApplicationForm,
  approvals: [
    {
      id: 'approval-1',
      department: 'GM',
      level: 1,
      requiredRole: 'JOB_APPROVER_GM',
      approverId: null,
      decision: 'PENDING',
      autoApproved: false,
      autoApprovalReason: null,
      comments: null,
      decidedAt: null,
      createdAt: '2026-03-01T08:00:00.000Z',
    },
    {
      id: 'approval-2',
      department: 'HR',
      level: 1,
      requiredRole: 'JOB_APPROVER_HR',
      approverId: null,
      decision: 'PENDING',
      autoApproved: false,
      autoApprovalReason: null,
      comments: null,
      decidedAt: null,
      createdAt: '2026-03-01T08:00:00.000Z',
    },
    {
      id: 'approval-3',
      department: 'FINANCE',
      level: 1,
      requiredRole: 'JOB_APPROVER_FINANCE',
      approverId: null,
      decision: 'PENDING',
      autoApproved: false,
      autoApprovalReason: null,
      comments: null,
      decidedAt: null,
      createdAt: '2026-03-01T08:00:00.000Z',
    },
  ],
};

const jobs: JobResponseDto[] = [
  {
    ...baseJob,
    requestForm: {
      id: 'req-1',
      jobTitle: 'Marketing Manager',
      department: 'digital_marketing',
      requestedBy: 'Jessica Parker',
      position: 'marketing_manager',
      requestType: 'NEW',
      replaceForUserId: null,
      businessJustification:
        'Scale regional demand generation and brand performance.',
      employmentType: 'FULL_TIME',
      workMode: 'ON_SITE',
      urgency: 'HIGH',
      neededByDate: '2026-04-10',
      status: {
        workflow: 'PENDING_FOR_APPROVAL',
        approvals: {
          finance: 'PENDING_FOR_APPROVAL',
          gm: 'PENDING_FOR_APPROVAL',
          hr: 'PENDING_FOR_APPROVAL',
        },
      },
      priority: 'HIGH',
      draftedAt: null,
      pendingApprovalAt: '2026-03-05T09:00:00.000Z',
      readyToPostAt: null,
      rejectedAt: null,
    },
    job: {
      id: 'job-1',
      title: 'Marketing Manager',
      slug: 'marketing-manager',
      departmentId: 'digital_marketing',
      positionId: 'marketing_manager',
      description: {
        type: 'doc',
        version: 1,
        content: [
          { type: 'paragraph', text: 'Lead regional marketing efforts.' },
        ],
      },
      summary: {
        type: 'doc',
        version: 1,
        content: [
          { type: 'paragraph', text: 'Own demand gen and brand programs.' },
        ],
      },
      experienceLevel: 'SENIOR',
      contractType: 'PERMANENT',
      employmentType: 'FULL_TIME',
      workLocationType: 'ON_SITE',
      city: 'Nairobi',
      country: 'Kenya',
      openings: 1,
      salaryMin: '3000',
      salaryMax: '4200',
      currency: 'USD',
      salaryMode: 'COMPETITIVE',
      benefits: ['Health insurance', 'Learning budget'],
      requiredSkills: ['Digital Marketing', 'Analytics'],
      preferredSkills: ['Lifecycle Automation'],
      responsibilities: ['Lead campaigns', 'Manage pipeline reporting'],
      tools: ['HubSpot', 'Google Analytics'],
      hiringManagerId: null,
      creatorIsHr: true,
      publishedAt: null,
      closedAt: null,
      closingReason: null,
      viewsCount: 0,
      applicationsCount: 0,
      shortlistedCount: 0,
      interviewsCount: 0,
      offersCount: 0,
      hiresCount: 0,
      createdById: null,
      applicationDeadline: '2026-04-30T23:59:59.000Z',
      createdAt: '2026-03-01T08:00:00.000Z',
      updatedAt: '2026-03-02T10:00:00.000Z',
    },
  },
  {
    ...baseJob,
    requestForm: {
      id: 'req-2',
      jobTitle: 'Senior Software Engineer',
      department: 'technical',
      requestedBy: 'Alice Njeri',
      position: 'backend_engineer',
      requestType: 'NEW',
      replaceForUserId: null,
      businessJustification: 'Scale backend delivery for Q2 launches.',
      employmentType: 'FULL_TIME',
      workMode: 'HYBRID',
      urgency: 'HIGH',
      neededByDate: '2026-04-20',
      status: {
        workflow: 'PENDING_FOR_APPROVAL',
        approvals: {
          finance: 'PENDING_FOR_APPROVAL',
          gm: 'PENDING_FOR_APPROVAL',
          hr: 'PENDING_FOR_APPROVAL',
        },
      },
      priority: 'MEDIUM',
      draftedAt: null,
      pendingApprovalAt: '2026-03-06T11:00:00.000Z',
      readyToPostAt: null,
      rejectedAt: null,
    },
    job: {
      id: 'job-2',
      title: 'Senior Software Engineer',
      slug: 'senior-software-engineer',
      departmentId: 'technical',
      positionId: 'backend_engineer',
      description: {
        type: 'doc',
        version: 1,
        content: [
          { type: 'paragraph', text: 'Own backend services and delivery.' },
        ],
      },
      summary: {
        type: 'doc',
        version: 1,
        content: [
          { type: 'paragraph', text: 'Scale critical platform systems.' },
        ],
      },
      experienceLevel: 'SENIOR',
      contractType: 'PERMANENT',
      employmentType: 'FULL_TIME',
      workLocationType: 'HYBRID',
      city: 'Addis Ababa',
      country: 'Ethiopia',
      openings: 1,
      salaryMin: '3000',
      salaryMax: '4200',
      currency: 'USD',
      salaryMode: 'NEGOTIABLE',
      benefits: ['Health insurance', 'Hybrid support'],
      requiredSkills: ['TypeScript', 'Node.js'],
      preferredSkills: ['Kubernetes'],
      responsibilities: ['Design services', 'Improve reliability'],
      tools: ['Docker', 'GitHub Actions'],
      hiringManagerId: null,
      creatorIsHr: true,
      publishedAt: null,
      closedAt: null,
      closingReason: null,
      viewsCount: 0,
      applicationsCount: 0,
      shortlistedCount: 0,
      interviewsCount: 0,
      offersCount: 0,
      hiresCount: 0,
      createdById: null,
      applicationDeadline: '2026-05-10T23:59:59.000Z',
      createdAt: '2026-03-02T08:00:00.000Z',
      updatedAt: '2026-03-03T10:00:00.000Z',
    },
  },
  {
    ...baseJob,
    requestForm: {
      id: 'req-3',
      jobTitle: 'Product Manager',
      department: 'technical',
      requestedBy: 'Mercy Wanjiku',
      position: 'product_manager',
      requestType: 'REPLACEMENT',
      replaceForUserId: 'emp-mercy-wanjiku',
      businessJustification: 'Own roadmap execution for HR automation.',
      employmentType: 'FULL_TIME',
      workMode: 'ON_SITE',
      urgency: 'MEDIUM',
      neededByDate: '2026-04-01',
      status: {
        workflow: 'REJECTED',
        approvals: {
          finance: 'REJECTED',
          gm: 'PENDING_FOR_APPROVAL',
          hr: 'PENDING_FOR_APPROVAL',
        },
      },
      priority: 'LOW',
      draftedAt: null,
      pendingApprovalAt: '2026-03-01T08:00:00.000Z',
      readyToPostAt: null,
      rejectedAt: '2026-03-10T09:00:00.000Z',
    },
    job: {
      id: 'job-3',
      title: 'Product Manager',
      slug: 'product-manager',
      departmentId: 'technical',
      positionId: 'product_manager',
      description: {
        type: 'doc',
        version: 1,
        content: [
          { type: 'paragraph', text: 'Lead roadmap planning and execution.' },
        ],
      },
      summary: {
        type: 'doc',
        version: 1,
        content: [
          { type: 'paragraph', text: 'Drive cross-functional delivery.' },
        ],
      },
      experienceLevel: 'MID',
      contractType: 'PERMANENT',
      employmentType: 'FULL_TIME',
      workLocationType: 'ON_SITE',
      city: 'Nairobi',
      country: 'Kenya',
      openings: 1,
      salaryMin: '0',
      salaryMax: '0',
      currency: '',
      salaryMode: 'NOT_SPECIFIED',
      benefits: ['Medical cover'],
      requiredSkills: ['Product Strategy', 'Stakeholder Management'],
      preferredSkills: ['Workflow automation'],
      responsibilities: ['Define roadmap', 'Coordinate delivery'],
      tools: ['Jira', 'Notion'],
      hiringManagerId: null,
      creatorIsHr: true,
      publishedAt: null,
      closedAt: '2026-03-10T09:00:00.000Z',
      closingReason: 'Rejected at finance review',
      viewsCount: 0,
      applicationsCount: 0,
      shortlistedCount: 0,
      interviewsCount: 0,
      offersCount: 0,
      hiresCount: 0,
      createdById: null,
      applicationDeadline: '2026-04-10T23:59:59.000Z',
      createdAt: '2026-03-01T08:00:00.000Z',
      updatedAt: '2026-03-10T09:00:00.000Z',
    },
  },
];

export const mockListJobsResponse: ListJobsResponse = {
  success: true,
  message: 'List of jobs',
  data: jobs,
  error: null,
  meta: {
    timestamp: '2026-03-10T09:30:00.000Z',
    requestId: 'mock-request-id',
    version: 'v1',
  },
};
