import type { ActiveJobItem } from "@/features/hr/recruitment/active-posting/types";

export const activePostingJobs: ActiveJobItem[] = [
  {
    id: "job-marketing-manager-001",
    title: "Marketing Manager",
    levelTag: "Intern",
    statusLabel: "Active Job",
    department: "Digital Marketing Dept.",
    employmentType: "Full-time",
    workMode: "On-site",
    openings: 1,
    applicantsCount: 124,
    viewsCount: 1420,
    postedAt: "2023-12-01",
    closesAt: "2024-01-30",
    priority: "high",
    summary:
      "We're looking for an experienced Frontend Developer to join our team and help build the next generation of our product platform.",
    keyResponsibilities: [
      "We're looking for an experienced Frontend Developer to join our team and help build the next generation of our product platform.",
      "We're looking for an experienced Frontend Developer to join our team and help build the next generation of our product platform.",
    ],
    requirements: [
      "7+ years in marketing",
      "Experience with digital marketing",
      "Strong analytical skills",
      "Team leadership experience",
    ],
    benefits: [
      "Competitive salary",
      "Health insurance",
      "Remote work",
      "Professional development budget",
    ],
    applicants: [
      {
        id: "a1",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        appliedAt: "Feb 24, 2025",
        yearsOfExperience: "7 years",
        salaryExpectation: "15,000",
        aiScore: 94,
      },
      {
        id: "a2",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        appliedAt: "Feb 24, 2025",
        yearsOfExperience: "7 years",
        salaryExpectation: "15,000",
        aiScore: 91,
      },
      {
        id: "a3",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        appliedAt: "Feb 24, 2025",
        yearsOfExperience: "7 years",
        salaryExpectation: "15,000",
        aiScore: 88,
      },
      {
        id: "a4",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        appliedAt: "Feb 24, 2025",
        yearsOfExperience: "7 years",
        salaryExpectation: "15,000",
        aiScore: 84,
      },
      {
        id: "a5",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        appliedAt: "Feb 24, 2025",
        yearsOfExperience: "7 years",
        salaryExpectation: "15,000",
        aiScore: 79,
      },
      {
        id: "a6",
        fullName: "Alex Johnson",
        phone: "+251 967 97 3799",
        appliedAt: "Feb 24, 2025",
        yearsOfExperience: "7 years",
        salaryExpectation: "15,000",
        aiScore: 73,
      },
    ],
    analytics: [
      { label: "Views", value: 1683 },
      { label: "Applications", value: 148 },
      { label: "Shortlisted", value: 26 },
      { label: "Offers", value: 4 },
    ],
    topMatch: {
      fullName: "Jessica Parker",
      phone: "+251 967 97 3799",
      experience: "2 Years",
      salaryExpectation: "20,000",
      canStart: "Feb 03, 2025",
      matchScore: 90,
    },
    pipelineStats: {
      total: 156,
      interviewed: 12,
      shortlist: 5,
      rejected: 144,
    },
    applicationFrequency: [
      { month: "Jan", applications: 125 },
      { month: "Feb", applications: 136 },
      { month: "Mar", applications: 148 },
      { month: "Apr", applications: 95 },
      { month: "May", applications: 142 },
      { month: "Jun", applications: 136 },
      { month: "Jul", applications: 166 },
      { month: "Aug", applications: 112 },
      { month: "Sep", applications: 139 },
      { month: "Oct", applications: 145 },
      { month: "Nov", applications: 136 },
      { month: "Dec", applications: 102 },
    ],
    salaryDistribution: [
      { range: "<10K", value: 28 },
      { range: "10-15K", value: 45 },
      { range: "15-20K", value: 38 },
      { range: ">20K", value: 15 },
    ],
    genderDistribution: [
      { name: "Male", value: 68, fill: "#1e66f7" },
      { name: "Female", value: 56, fill: "#a0bfff" },
    ],
    experienceDistribution: [
      { range: "0-2 years", value: 15, fill: "#a9e638" },
      { range: "3-5 years", value: 43, fill: "#2e68e6" },
      { range: "6-10 years", value: 49, fill: "#f0d43a" },
      { range: "10+ years", value: 19, fill: "#95afe3" },
    ],
  },
  {
    id: "job-ui-ux-designer-002",
    title: "UI/UX Designer",
    levelTag: "Senior",
    statusLabel: "Active Job",
    department: "Creative Dept.",
    employmentType: "Full-time",
    workMode: "Hybrid",
    openings: 2,
    applicantsCount: 86,
    viewsCount: 910,
    postedAt: "2024-02-11",
    closesAt: "2024-03-25",
    priority: "medium",
    summary:
      "We're looking for a product-focused UI/UX Designer to lead user research, wireframing, and polished interface design for core HR workflows.",
    keyResponsibilities: [
      "Plan and execute user research sessions across hiring and onboarding modules.",
      "Create low and high-fidelity design systems aligned with product goals.",
    ],
    requirements: [
      "5+ years in product design",
      "Strong Figma and prototyping skills",
      "Portfolio of shipped B2B workflows",
      "Strong collaboration with engineers",
    ],
    benefits: [
      "Competitive salary",
      "Health insurance",
      "Hybrid work model",
      "Annual design conference budget",
    ],
    applicants: [
      {
        id: "b1",
        fullName: "Mina Bekele",
        phone: "+251 910 22 1188",
        appliedAt: "Mar 02, 2025",
        yearsOfExperience: "6 years",
        salaryExpectation: "18,500",
        aiScore: 92,
      },
      {
        id: "b2",
        fullName: "Samuel Tadesse",
        phone: "+251 923 10 9876",
        appliedAt: "Mar 01, 2025",
        yearsOfExperience: "5 years",
        salaryExpectation: "16,000",
        aiScore: 81,
      },
    ],
    analytics: [
      { label: "Views", value: 910 },
      { label: "Applications", value: 86 },
      { label: "Shortlisted", value: 19 },
      { label: "Offers", value: 2 },
    ],
    topMatch: {
      fullName: "Mina Bekele",
      phone: "+251 910 22 1188",
      experience: "6 Years",
      salaryExpectation: "18,500",
      canStart: "Mar 20, 2025",
      matchScore: 88,
    },
    pipelineStats: {
      total: 86,
      interviewed: 18,
      shortlist: 7,
      rejected: 61,
    },
    applicationFrequency: [
      { month: "Jan", applications: 60 },
      { month: "Feb", applications: 65 },
      { month: "Mar", applications: 70 },
      { month: "Apr", applications: 58 },
      { month: "May", applications: 72 },
      { month: "Jun", applications: 66 },
      { month: "Jul", applications: 78 },
      { month: "Aug", applications: 62 },
      { month: "Sep", applications: 74 },
      { month: "Oct", applications: 71 },
      { month: "Nov", applications: 69 },
      { month: "Dec", applications: 55 },
    ],
    salaryDistribution: [
      { range: "<10K", value: 12 },
      { range: "10-15K", value: 26 },
      { range: "15-20K", value: 31 },
      { range: ">20K", value: 17 },
    ],
    genderDistribution: [
      { name: "Male", value: 35, fill: "#1e66f7" },
      { name: "Female", value: 51, fill: "#a0bfff" },
    ],
    experienceDistribution: [
      { range: "0-2 years", value: 9, fill: "#a9e638" },
      { range: "3-5 years", value: 24, fill: "#2e68e6" },
      { range: "6-10 years", value: 38, fill: "#f0d43a" },
      { range: "10+ years", value: 15, fill: "#95afe3" },
    ],
  },
  {
    id: "job-data-analyst-003",
    title: "Data Analyst",
    levelTag: "Mid-level",
    statusLabel: "Active Job",
    department: "Technical Dept.",
    employmentType: "Hybrid",
    workMode: "Remote",
    openings: 1,
    applicantsCount: 64,
    viewsCount: 744,
    postedAt: "2024-02-18",
    closesAt: "2024-03-30",
    priority: "high",
    summary:
      "We're hiring a Data Analyst to support people analytics, recruitment metrics, and executive reporting with reliable dashboards and insights.",
    keyResponsibilities: [
      "Develop dashboards for hiring funnels, conversion rates, and cycle time.",
      "Partner with HR and operations teams to define actionable KPIs.",
    ],
    requirements: [
      "3+ years in analytics roles",
      "Advanced SQL and spreadsheet skills",
      "Experience with BI tools",
      "Strong communication and storytelling",
    ],
    benefits: [
      "Performance bonus",
      "Health insurance",
      "Learning stipend",
      "Flexible working hours",
    ],
    applicants: [
      {
        id: "c1",
        fullName: "Naol Girma",
        phone: "+251 911 67 3401",
        appliedAt: "Mar 03, 2025",
        yearsOfExperience: "4 years",
        salaryExpectation: "14,000",
        aiScore: 89,
      },
      {
        id: "c2",
        fullName: "Helen Assefa",
        phone: "+251 929 88 4410",
        appliedAt: "Mar 02, 2025",
        yearsOfExperience: "5 years",
        salaryExpectation: "15,500",
        aiScore: 86,
      },
    ],
    analytics: [
      { label: "Views", value: 744 },
      { label: "Applications", value: 64 },
      { label: "Shortlisted", value: 11 },
      { label: "Offers", value: 1 },
    ],
    topMatch: {
      fullName: "Helen Assefa",
      phone: "+251 929 88 4410",
      experience: "5 Years",
      salaryExpectation: "15,500",
      canStart: "Mar 15, 2025",
      matchScore: 86,
    },
    pipelineStats: {
      total: 64,
      interviewed: 11,
      shortlist: 4,
      rejected: 49,
    },
    applicationFrequency: [
      { month: "Jan", applications: 44 },
      { month: "Feb", applications: 49 },
      { month: "Mar", applications: 53 },
      { month: "Apr", applications: 40 },
      { month: "May", applications: 55 },
      { month: "Jun", applications: 48 },
      { month: "Jul", applications: 59 },
      { month: "Aug", applications: 42 },
      { month: "Sep", applications: 56 },
      { month: "Oct", applications: 58 },
      { month: "Nov", applications: 51 },
      { month: "Dec", applications: 39 },
    ],
    salaryDistribution: [
      { range: "<10K", value: 10 },
      { range: "10-15K", value: 29 },
      { range: "15-20K", value: 19 },
      { range: ">20K", value: 6 },
    ],
    genderDistribution: [
      { name: "Male", value: 37, fill: "#1e66f7" },
      { name: "Female", value: 27, fill: "#a0bfff" },
    ],
    experienceDistribution: [
      { range: "0-2 years", value: 14, fill: "#a9e638" },
      { range: "3-5 years", value: 26, fill: "#2e68e6" },
      { range: "6-10 years", value: 18, fill: "#f0d43a" },
      { range: "10+ years", value: 6, fill: "#95afe3" },
    ],
  },
];
